server:
  port: 9900
spring:
  datasource:
    url: ${JDBC_URL}
    password: ${JDBC_PASSWORD}
    username: ${JDBC_USERNAME}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
